/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Data.ProdutoData;
import Model.TabelaProduto;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class JTabelaProduto extends javax.swing.JFrame {

    private TabelaProduto objFun3;
    private ProdutoData DAO3;
    private int action = 0;
    
    public JTabelaProduto() {
        initComponents();
        DAO3 = new ProdutoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pesquisar = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        DescricaoField = new javax.swing.JTextField();
        Endereco = new javax.swing.JLabel();
        IngredienteField1 = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        IngredienteField2 = new javax.swing.JTextField();
        CPF = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        PesquisarB = new javax.swing.JButton();
        NovoB = new javax.swing.JButton();
        EditarB = new javax.swing.JButton();
        DeletarB = new javax.swing.JButton();
        CancelarB = new javax.swing.JButton();
        SalvarB = new javax.swing.JButton();
        IngredienteField3 = new javax.swing.JTextField();
        Email1 = new javax.swing.JLabel();
        Email2 = new javax.swing.JLabel();
        IngredienteField4 = new javax.swing.JTextField();
        ValorField = new javax.swing.JTextField();
        TabelaB = new javax.swing.JButton();
        VoltarB = new javax.swing.JButton();
        Check1 = new javax.swing.JCheckBox();
        Check2 = new javax.swing.JCheckBox();
        Check3 = new javax.swing.JCheckBox();

        Pesquisar.setText("jButton1");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });

        jToggleButton1.setText("jToggleButton1");

        jToggleButton4.setText("ON");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Produtos");

        Nome.setText("Descrição do pedido:");

        DescricaoField.setEnabled(false);
        DescricaoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescricaoFieldActionPerformed(evt);
            }
        });

        Endereco.setText("Ingrediente 1:");

        IngredienteField1.setEnabled(false);
        IngredienteField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngredienteField1ActionPerformed(evt);
            }
        });

        Email.setText("Ingrediente 3:");

        IngredienteField2.setEnabled(false);
        IngredienteField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngredienteField2ActionPerformed(evt);
            }
        });

        CPF.setText("Ingrediente 2:");

        ID.setText("ID do produto:");

        IDField.setDoubleBuffered(true);
        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });

        PesquisarB.setLabel("Pesquisar");
        PesquisarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarBActionPerformed(evt);
            }
        });

        NovoB.setText("Novo");
        NovoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoBActionPerformed(evt);
            }
        });

        EditarB.setText("Editar");
        EditarB.setEnabled(false);
        EditarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBActionPerformed(evt);
            }
        });

        DeletarB.setText("Deletar");
        DeletarB.setEnabled(false);
        DeletarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarBActionPerformed(evt);
            }
        });

        CancelarB.setText("Cancelar");
        CancelarB.setEnabled(false);
        CancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBActionPerformed(evt);
            }
        });

        SalvarB.setText("Salvar");
        SalvarB.setEnabled(false);
        SalvarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBActionPerformed(evt);
            }
        });

        IngredienteField3.setEnabled(false);
        IngredienteField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngredienteField3ActionPerformed(evt);
            }
        });

        Email1.setText("Valor do produto:");

        Email2.setText("Ingrediente 4:");

        IngredienteField4.setEnabled(false);
        IngredienteField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngredienteField4ActionPerformed(evt);
            }
        });

        ValorField.setDoubleBuffered(true);
        ValorField.setEnabled(false);
        ValorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorFieldActionPerformed(evt);
            }
        });

        TabelaB.setText("Tabela");
        TabelaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TabelaBActionPerformed(evt);
            }
        });

        VoltarB.setText("Voltar");
        VoltarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBActionPerformed(evt);
            }
        });

        Check1.setEnabled(false);
        Check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check1ActionPerformed(evt);
            }
        });

        Check2.setEnabled(false);

        Check3.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(143, 143, 143)
                        .addComponent(VoltarB))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Nome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DescricaoField))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Endereco)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(IngredienteField1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Email2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(IngredienteField4))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Email)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(IngredienteField3))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(CPF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(IngredienteField2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Check1)
                                .addComponent(Check2)
                                .addComponent(Check3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Email1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ValorField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SalvarB)
                                .addGap(18, 18, 18)
                                .addComponent(DeletarB)
                                .addGap(18, 18, 18)
                                .addComponent(TabelaB))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(NovoB)
                                .addGap(18, 18, 18)
                                .addComponent(EditarB)
                                .addGap(18, 18, 18)
                                .addComponent(CancelarB)
                                .addGap(2, 2, 2)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PesquisarB))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(VoltarB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesquisarB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nome)
                            .addComponent(DescricaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Endereco)
                            .addComponent(IngredienteField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IngredienteField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CPF)))
                    .addComponent(Check1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Email)
                                .addComponent(IngredienteField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Check2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IngredienteField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email2)))
                    .addComponent(Check3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email1))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarB)
                    .addComponent(NovoB)
                    .addComponent(CancelarB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarB)
                    .addComponent(DeletarB)
                    .addComponent(TabelaB))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DescricaoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescricaoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescricaoFieldActionPerformed

    private void IngredienteField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngredienteField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngredienteField1ActionPerformed

    private void IngredienteField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngredienteField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngredienteField2ActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesquisarActionPerformed

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDFieldActionPerformed

    private void PesquisarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarBActionPerformed
try{
      if (IDField.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Caixa vazia, não foi possível efetuar a pesquisa");
      IDField.requestFocus();
      }else{
          TabelaProduto objFun = DAO3.Pesquisar3(Integer.parseInt(IDField.getText()));
          if(objFun == null){
              JOptionPane.showMessageDialog(this, "Registro não encontrado");
              IDField.setText("");
              IDField.requestFocus();
          }else{
              IngredienteField1.setText(objFun.getIngrediente1());
              IngredienteField2.setText(objFun.getIngrediente2());
              IngredienteField3.setText(objFun.getIngrediente3());
              IngredienteField4.setText(objFun.getIngrediente4());
              DescricaoField.setText(objFun.getDescricao());
              ValorField.setText((objFun.getValor_do_Produto() + ""));
              CancelarB.setEnabled(true);
              EditarB.setEnabled(true);
              DeletarB.setEnabled(true);
              PesquisarB.setEnabled(true);
              NovoB.setEnabled(false);
              SalvarB.setEnabled(false);
              IngredienteField1.setEnabled(false);
              IngredienteField2.setEnabled(false);
              IngredienteField3.setEnabled(false);
              IngredienteField4.setEnabled(false);
              DescricaoField.setEnabled(false);
              ValorField.setEnabled(false);
              IDField.setEnabled(true);
          }
          
      }
    }catch(Exception error){
        JOptionPane.showMessageDialog(this, "Erro:" + error.getMessage());
        }
    }//GEN-LAST:event_PesquisarBActionPerformed

    private void NovoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoBActionPerformed
CancelarB.setEnabled(true);
EditarB.setEnabled(false);
DeletarB.setEnabled(false);
PesquisarB.setEnabled(false);
NovoB.setEnabled(false);
SalvarB.setEnabled(true);
DescricaoField.setEnabled(true);
IngredienteField1.setEnabled(true);
IngredienteField2.setEnabled(true);
IngredienteField3.setEnabled(true);
IngredienteField4.setEnabled(true);
ValorField.setEnabled(true);
IDField.setEnabled(false);
IDField.setText("");
Check1.setEnabled(true);
Check2.setEnabled(true);
Check3.setEnabled(true);
action = 1;
    }//GEN-LAST:event_NovoBActionPerformed

    private void EditarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBActionPerformed
              CancelarB.setEnabled(true);
              EditarB.setEnabled(false);
              DeletarB.setEnabled(false);
              PesquisarB.setEnabled(false);
              NovoB.setEnabled(false);
              SalvarB.setEnabled(true);
              DescricaoField.setEnabled(true);
              IngredienteField1.setEnabled(true);
              IngredienteField2.setEnabled(true);
              IngredienteField3.setEnabled(true);
              IngredienteField4.setEnabled(true);
              Check1.setEnabled(true);
              Check2.setEnabled(true);
              Check3.setEnabled(true);
              ValorField.setEnabled(true);
              IDField.setEnabled(false);
              action = 2;
    }//GEN-LAST:event_EditarBActionPerformed

    private void DeletarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarBActionPerformed
        try{
        if(IDField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo ID vazio");
        }else{
        if(!(DAO3.Deletar(Integer.parseInt(IDField.getText())))){
            JOptionPane.showMessageDialog(this, "Não foi possível excluir o registro");
        }else{
            JOptionPane.showMessageDialog(this, "Registro excluído com sucesso");
            CancelarB.setEnabled(false);
            EditarB.setEnabled(false);
            DeletarB.setEnabled(false);
            PesquisarB.setEnabled(true);
            NovoB.setEnabled(true);
            SalvarB.setEnabled(false);
            DescricaoField.setEnabled(false);
            IngredienteField1.setEnabled(false);
            IngredienteField2.setEnabled(false);
            IngredienteField3.setEnabled(false);
            IngredienteField4.setEnabled(false);
            ValorField.setEnabled(false);
            IDField.setEnabled(true);
            IDField.setText("");
            DescricaoField.setText("");
            IngredienteField1.setText("");
            IngredienteField2.setText("");
            IngredienteField3.setText("");
            IngredienteField4.setText("");
            ValorField.setText("");
            Check1.setEnabled(false);
            Check2.setEnabled(false);
            Check3.setEnabled(false);
        }}}
        catch(Exception error){
            JOptionPane.showMessageDialog(this, "erro: " + error.getMessage());
        }
    }//GEN-LAST:event_DeletarBActionPerformed

    private void CancelarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBActionPerformed
CancelarB.setEnabled(false);
EditarB.setEnabled(false);
DeletarB.setEnabled(false);
PesquisarB.setEnabled(true);
NovoB.setEnabled(true);
SalvarB.setEnabled(false);
DescricaoField.setEnabled(false);
IngredienteField1.setEnabled(false);
IngredienteField2.setEnabled(false);
IngredienteField3.setEnabled(false);
IngredienteField4.setEnabled(false);
ValorField.setEnabled(false);
IDField.setEnabled(true);
IDField.setText("");
DescricaoField.setText("");
IngredienteField1.setText("");
IngredienteField2.setText("");
IngredienteField3.setText("");
IngredienteField4.setText("");
ValorField.setText("");
Check1.setEnabled(false);
Check2.setEnabled(false);
Check3.setEnabled(false);
Check1.setSelected(false);
Check2.setSelected(false);
Check3.setSelected(false);
    }//GEN-LAST:event_CancelarBActionPerformed

    private void SalvarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBActionPerformed
try{
            if (Checagem()) {
                if (action == 1){
            if(SalvarCampos()){
                
                    if(DAO3.Input3(objFun3)){
                        
                        
                        JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
                        CancelarB.setEnabled(false);
                        EditarB.setEnabled(false);
                        DeletarB.setEnabled(false);
                        PesquisarB.setEnabled(true);
                        NovoB.setEnabled(true);
                        SalvarB.setEnabled(false);
                        DescricaoField.setEnabled(false);
                        IngredienteField1.setEnabled(false);
                        IngredienteField2.setEnabled(false);
                        IngredienteField3.setEnabled(false);
                        IngredienteField4.setEnabled(false);
                        ValorField.setEnabled(false);
                        IDField.setEnabled(true);
                        IDField.setText("");
                        DescricaoField.setText("");
                        IngredienteField1.setText("");
                        IngredienteField2.setText("");
                        IngredienteField3.setText("");
                        IngredienteField4.setText("");
                        ValorField.setText("");
                        Check1.setEnabled(false);
                        Check2.setEnabled(false);
                        Check3.setEnabled(false);}
                        Check1.setSelected(false);
                        Check2.setSelected(false);
                        Check3.setSelected(false);
               
                } else{ 
            JOptionPane.showMessageDialog(this, "Não foi possível salvar o registro");
        }
              }
        
        
       
            if (action == 2){
                 if(SalvarCampos2()){
                
                    if(DAO3.Editar3(objFun3)){

                        JOptionPane.showMessageDialog(this, "Editado com sucesso!");
                        CancelarB.setEnabled(false);
                        EditarB.setEnabled(false);
                        DeletarB.setEnabled(false);
                        PesquisarB.setEnabled(true);
                        NovoB.setEnabled(true);
                        SalvarB.setEnabled(false);
                        DescricaoField.setEnabled(false);
                        IngredienteField1.setEnabled(false);
                        IngredienteField2.setEnabled(false);
                        IngredienteField3.setEnabled(false);
                        IngredienteField4.setEnabled(false);
                        ValorField.setEnabled(false);
                        IDField.setEnabled(true);
                        IDField.setText("");
                        DescricaoField.setText("");
                        IngredienteField1.setText("");
                        IngredienteField2.setText("");
                        IngredienteField3.setText("");
                        IngredienteField4.setText("");
                        ValorField.setText("");
                        Check1.setEnabled(false);
                        Check2.setEnabled(false);
                        Check3.setEnabled(false);
                        Check1.setSelected(false);
                        Check2.setSelected(false);
                        Check3.setSelected(false);}
               
                
                 }else{ 
            JOptionPane.showMessageDialog(this, "Não foi possível editar o registro");
                } 
           
                 }}} catch (Exception ex) {
            
                    JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
                    Logger.getLogger(JTabelaCliente.class.getName()).log(Level.SEVERE, null, ex);}
        
    }//GEN-LAST:event_SalvarBActionPerformed

    private void IngredienteField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngredienteField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngredienteField3ActionPerformed

    private void IngredienteField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngredienteField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngredienteField4ActionPerformed

    private void ValorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorFieldActionPerformed

    private void VoltarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBActionPerformed
Menu VoltaMenu = new Menu();
VoltaMenu.show();
dispose();
    }//GEN-LAST:event_VoltarBActionPerformed

    private void TabelaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TabelaBActionPerformed
ShowTabelaProduto TabelaProdutoShow = new ShowTabelaProduto();
TabelaProdutoShow.show();
dispose();
    }//GEN-LAST:event_TabelaBActionPerformed

    private void Check1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check1ActionPerformed

    }//GEN-LAST:event_Check1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTabelaProduto().setVisible(true);
            }
        });
    }
    
    public boolean Checagem(){
        if (IngredienteField1.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo Ingrediente1 falta ser preenchido!");
            return false;}
        if (IngredienteField2.getText().equals("")){
            if(Check1Listener()){
            return true;    
            }
            if(!(Check1Listener())){JOptionPane.showMessageDialog(this, "Campo Ingrediente2 falta ser preenchido!");
            return false;}}
        if (IngredienteField3.getText().equals("")){
            if(Check2Listener()){
            return true;    
            }
            if(!(Check2Listener())){JOptionPane.showMessageDialog(this, "Campo Ingrediente3 falta ser preenchido!");
            return false;}}
        if (IngredienteField4.getText().equals("")){
            if(Check3Listener()){
            return true;    
            }
            if(!(Check3Listener())){JOptionPane.showMessageDialog(this, "Campo Ingrediente4 falta ser preenchido!");
            return false;}}
        if (DescricaoField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo Descrição falta ser preenchido!");
            return false;}
        if (ValorField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo Valor_do_Produto falta ser preenchido!");
            return false;}
        
        
        
        return true;

}
    
private boolean Check1Listener(){
    boolean Check1L = Check1.isSelected();
    
    if (Check1L = false){
    return true;}
    else
    return false;
}

private boolean Check2Listener(){
    boolean Check2L = Check2.isSelected();
    
    if (Check2L = false){
    return true;}
    else
    return false;
}

private boolean Check3Listener(){
    boolean Check3L = Check1.isSelected();
    
    if (Check3L = false){
    return true;}
    else
    return false;
}
public boolean SalvarCampos(){
        Check1Listener();
        Check2Listener();
        Check3Listener();
        objFun3 = new TabelaProduto();
        objFun3.setIngrediente1(IngredienteField1.getText());
        if(!(Check1Listener())){objFun3.setIngrediente2(IngredienteField2.getText());}
        else{objFun3.setIngrediente2("");}
        if(!(Check2Listener())){objFun3.setIngrediente3(IngredienteField3.getText());}
        else{objFun3.setIngrediente3("");}
        if(!(Check3Listener())){objFun3.setIngrediente4(IngredienteField4.getText());}
        else{objFun3.setIngrediente4("");}
        objFun3.setDescricao(DescricaoField.getText());
        objFun3.setValor_do_Produto(Double.parseDouble(ValorField.getText()));
    
    return true;
    }
    
     public boolean SalvarCampos2(){
        
        objFun3 = new TabelaProduto();
        objFun3.setID_do_Produto(Integer.parseInt(IDField.getText()));
        objFun3.setIngrediente1(IngredienteField1.getText());
        objFun3.setIngrediente1(IngredienteField2.getText());;
        objFun3.setIngrediente1(IngredienteField3.getText());
        objFun3.setIngrediente1(IngredienteField4.getText());
        objFun3.setDescricao(DescricaoField.getText());
        objFun3.setValor_do_Produto(Double.parseDouble(ValorField.getText()));
    
    return true;
    }   
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPF;
    private javax.swing.JButton CancelarB;
    private javax.swing.JCheckBox Check1;
    private javax.swing.JCheckBox Check2;
    private javax.swing.JCheckBox Check3;
    private javax.swing.JButton DeletarB;
    private javax.swing.JTextField DescricaoField;
    private javax.swing.JButton EditarB;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Email1;
    private javax.swing.JLabel Email2;
    private javax.swing.JLabel Endereco;
    private javax.swing.JLabel ID;
    private javax.swing.JTextField IDField;
    private javax.swing.JTextField IngredienteField1;
    private javax.swing.JTextField IngredienteField2;
    private javax.swing.JTextField IngredienteField3;
    private javax.swing.JTextField IngredienteField4;
    private javax.swing.JLabel Nome;
    private javax.swing.JButton NovoB;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton PesquisarB;
    private javax.swing.JButton SalvarB;
    private javax.swing.JButton TabelaB;
    private javax.swing.JTextField ValorField;
    private javax.swing.JButton VoltarB;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
