/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.TabelaCliente;
import Data.ClienteData;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class JTabelaCliente extends javax.swing.JFrame {
    private int action = 0;
    private TabelaCliente objFun;
    private ClienteData DAO;
    
    public JTabelaCliente() {
        initComponents();
        DAO = new ClienteData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Pesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        NomeField = new javax.swing.JTextField();
        Endereco = new javax.swing.JLabel();
        EnderecoField = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        CPF = new javax.swing.JLabel();
        TelefoneField = new javax.swing.JFormattedTextField();
        Telefone = new javax.swing.JLabel();
        CPFField = new javax.swing.JFormattedTextField();
        ID = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        PesquisarB = new javax.swing.JButton();
        NovoB = new javax.swing.JButton();
        EditarB = new javax.swing.JButton();
        DeletarB = new javax.swing.JButton();
        CancelarB = new javax.swing.JButton();
        SalvarB = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bTabela = new javax.swing.JButton();

        Pesquisar.setText("jButton1");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de cliente");

        Nome.setText("Nome:");

        NomeField.setEnabled(false);
        NomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeFieldActionPerformed(evt);
            }
        });

        Endereco.setText("Endereço:");

        EnderecoField.setEnabled(false);
        EnderecoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnderecoFieldActionPerformed(evt);
            }
        });

        Email.setText("E-mail:");

        EmailField.setEnabled(false);
        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });

        CPF.setText("CPF:");

        try {
            TelefoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+55(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TelefoneField.setEnabled(false);
        TelefoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefoneFieldActionPerformed(evt);
            }
        });

        Telefone.setText("Telefone:");

        try {
            CPFField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CPFField.setToolTipText("");
        CPFField.setEnabled(false);
        CPFField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFFieldActionPerformed(evt);
            }
        });

        ID.setText("ID:");

        IDField.setDoubleBuffered(true);
        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });

        PesquisarB.setLabel("Pesquisar");
        PesquisarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarBActionPerformed(evt);
            }
        });

        NovoB.setText("Novo");
        NovoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoBActionPerformed(evt);
            }
        });

        EditarB.setText("Editar");
        EditarB.setEnabled(false);
        EditarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBActionPerformed(evt);
            }
        });

        DeletarB.setText("Deletar");
        DeletarB.setEnabled(false);
        DeletarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarBActionPerformed(evt);
            }
        });

        CancelarB.setText("Cancelar");
        CancelarB.setEnabled(false);
        CancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBActionPerformed(evt);
            }
        });

        SalvarB.setText("Salvar");
        SalvarB.setEnabled(false);
        SalvarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBActionPerformed(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bTabela.setText("Tabela");
        bTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Endereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EnderecoField)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailField)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NomeField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CPFField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Telefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TelefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PesquisarB))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NovoB)
                                        .addGap(18, 18, 18)
                                        .addComponent(EditarB)
                                        .addGap(18, 18, 18)
                                        .addComponent(CancelarB))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SalvarB)
                                        .addGap(18, 18, 18)
                                        .addComponent(DeletarB)
                                        .addGap(18, 18, 18)
                                        .addComponent(bTabela)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesquisarB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nome)
                    .addComponent(NomeField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Endereco)
                    .addComponent(EnderecoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CPF)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TelefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Telefone))
                    .addComponent(CPFField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoB)
                    .addComponent(EditarB)
                    .addComponent(CancelarB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarB)
                    .addComponent(DeletarB)
                    .addComponent(bTabela))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void NomeFieldActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void EnderecoFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void TelefoneFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void CPFFieldActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void PesquisarBActionPerformed(java.awt.event.ActionEvent evt) {                                           
    try{
      if (IDField.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Caixa vazia, não foi possível efetuar a pesquisa");
      IDField.requestFocus();
      }else{
          TabelaCliente objFun = DAO.Pesquisar(Integer.parseInt(IDField.getText()));
          if(objFun == null){
              JOptionPane.showMessageDialog(this, "Registro não encontrado");
              IDField.setText("");
              IDField.requestFocus();
          }else{
              NomeField.setText(objFun.getNome());
              EnderecoField.setText(objFun.getEndereco());
              EmailField.setText(objFun.getEmail());
              CPFField.setText(objFun.getCPF());
              TelefoneField.setText(objFun.getTelefone());
              CancelarB.setEnabled(true);
              EditarB.setEnabled(true);
              DeletarB.setEnabled(true);
              PesquisarB.setEnabled(true);
              NovoB.setEnabled(false);
              SalvarB.setEnabled(false);
              NomeField.setEnabled(false);
              EnderecoField.setEnabled(false);
              EmailField.setEnabled(false);
              CPFField.setEnabled(false);
              TelefoneField.setEnabled(false);
              IDField.setEnabled(true);
          }
          
      }
    }catch(Exception error){
        JOptionPane.showMessageDialog(this, "Erro:" + error.getMessage());
        }
    }                                          

    private void NovoBActionPerformed(java.awt.event.ActionEvent evt) {                                      
              CancelarB.setEnabled(true);
              EditarB.setEnabled(false);
              DeletarB.setEnabled(false);
              PesquisarB.setEnabled(false);
              NovoB.setEnabled(false);
              SalvarB.setEnabled(true);
              NomeField.setEnabled(true);
              EnderecoField.setEnabled(true);
              EmailField.setEnabled(true);
              CPFField.setEnabled(true);
              TelefoneField.setEnabled(true);
              IDField.setEnabled(false);
              bTabela.setEnabled(false);
              IDField.setText("");
              action = 1;

    }                                     

    private void EditarBActionPerformed(java.awt.event.ActionEvent evt) {                                        
              CancelarB.setEnabled(true);
              EditarB.setEnabled(false);
              DeletarB.setEnabled(true);
              PesquisarB.setEnabled(false);
              NovoB.setEnabled(false);
              SalvarB.setEnabled(true);
              NomeField.setEnabled(true);
              EnderecoField.setEnabled(true);
              EmailField.setEnabled(true);
              CPFField.setEnabled(true);
              TelefoneField.setEnabled(true);
              IDField.setEnabled(true);
              bTabela.setEnabled(false);
              action = 2;
    }                                       

    private void DeletarBActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try{
        if(IDField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo ID vazio");
        }else{
        if(DAO.Deletar(Integer.parseInt(IDField.getText()))){
JOptionPane.showMessageDialog(this, "Registro excluído com sucesso!");
CancelarB.setEnabled(false);
EditarB.setEnabled(false);
DeletarB.setEnabled(false);
PesquisarB.setEnabled(true);
NovoB.setEnabled(true);
SalvarB.setEnabled(false);
NomeField.setEnabled(false);
EnderecoField.setEnabled(false);
EmailField.setEnabled(false);
CPFField.setEnabled(false);
TelefoneField.setEnabled(false);
IDField.setEnabled(true);
bTabela.setEnabled(true);
NomeField.setText("");
EnderecoField.setText("");
EmailField.setText("");
CPFField.setText("");
TelefoneField.setText("");
IDField.setText("");
        }else{
            JOptionPane.showMessageDialog(this, "Não foi possível excluir o registro");
        }}}
        catch(Exception error){
            JOptionPane.showMessageDialog(this, "erro: " + error.getMessage());
        }
    }                                        

    private void CancelarBActionPerformed(java.awt.event.ActionEvent evt) {                                          
CancelarB.setEnabled(false);
EditarB.setEnabled(false);
DeletarB.setEnabled(false);
PesquisarB.setEnabled(true);
NovoB.setEnabled(true);
SalvarB.setEnabled(false);
NomeField.setEnabled(false);
EnderecoField.setEnabled(false);
EmailField.setEnabled(false);
CPFField.setEnabled(false);
TelefoneField.setEnabled(false);
IDField.setEnabled(true);
bTabela.setEnabled(true);
NomeField.setText("");
EnderecoField.setText("");
EmailField.setText("");
CPFField.setText("");
TelefoneField.setText("");
IDField.setText("");
    }                                         

    private void SalvarBActionPerformed(java.awt.event.ActionEvent evt) {                                        
     try {
            if (Checagem()) {
                if (action == 1){
            if(SalvarCampos()){
                
                    if(DAO.Input(objFun)){
                        
                        
                        JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
                        CancelarB.setEnabled(false);
                        EditarB.setEnabled(false);
                        DeletarB.setEnabled(false);
                        PesquisarB.setEnabled(true);
                        NovoB.setEnabled(true);
                        SalvarB.setEnabled(false);
                        NomeField.setEnabled(false);
                        EnderecoField.setEnabled(false);
                        EmailField.setEnabled(false);
                        CPFField.setEnabled(false);
                        TelefoneField.setEnabled(false);
                        IDField.setEnabled(true);
                        bTabela.setEnabled(true);
                        NomeField.setText("");
                        EnderecoField.setText("");
                        EmailField.setText("");
                        CPFField.setText("");
                        TelefoneField.setText("");}
               
                } else{ 
            JOptionPane.showMessageDialog(this, "Não foi possível salvar o registro");
        }
              }
        
        
       
            if (action == 2){
                 if(SalvarCampos2()){
                
                    if(DAO.Editar(objFun)){
                        
                        
                        JOptionPane.showMessageDialog(this, "Editado com sucesso!");
                        CancelarB.setEnabled(false);
                        EditarB.setEnabled(false);
                        DeletarB.setEnabled(false);
                        PesquisarB.setEnabled(true);
                        NovoB.setEnabled(true);
                        SalvarB.setEnabled(false);
                        NomeField.setEnabled(false);
                        EnderecoField.setEnabled(false);
                        EmailField.setEnabled(false);
                        CPFField.setEnabled(false);
                        TelefoneField.setEnabled(false);
                        IDField.setEnabled(true);
                        bTabela.setEnabled(true);
                        NomeField.setText("");
                        EnderecoField.setText("");
                        EmailField.setText("");
                        CPFField.setText("");
                        TelefoneField.setText("");}
               
                }
                else{ 
            JOptionPane.showMessageDialog(this, "Não foi possível editar o registro");
                }} 
           
            }} catch (Exception ex) {
            
                    JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
                    Logger.getLogger(JTabelaCliente.class.getName()).log(Level.SEVERE, null, ex);}
     
    }                                       

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    Menu VoltaMenu = new Menu();
    VoltaMenu.show();
    dispose();
    }                                        

    private void bTabelaActionPerformed(java.awt.event.ActionEvent evt) {                                        
ShowTabelaCliente TabelaClienteShow = new ShowTabelaCliente ();
TabelaClienteShow.show();
dispose();
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTabelaCliente().setVisible(true);
            }
        });
    }
    
    public boolean Checagem(){
        if (NomeField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo Nome falta ser preenchido!");
            return false;}
        if (EnderecoField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo Endereço falta ser preenchido!");
            return false;}
        if (EmailField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo Email falta ser preenchido!");
            return false;}
        if (CPFField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo CPF falta ser preenchido!");
            return false;}
        if (TelefoneField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo Telefone falta ser preenchido!");
            return false;}
        
        return true;

}
    
    public boolean SalvarCampos(){
        
        objFun = new TabelaCliente();
        objFun.setNome(NomeField.getText());
        objFun.setEndereco(EnderecoField.getText());
        objFun.setEmail(EmailField.getText());
        objFun.setCPF(CPFField.getText());
        objFun.setTelefone(TelefoneField.getText());
    
    return true;
    }
    
     public boolean SalvarCampos2(){
        
        objFun = new TabelaCliente();
        objFun.setID(Integer.parseInt(IDField.getText()));
        objFun.setNome(NomeField.getText());
        objFun.setEndereco(EnderecoField.getText());
        objFun.setEmail(EmailField.getText());
        objFun.setCPF(CPFField.getText());
        objFun.setTelefone(TelefoneField.getText());
    
    return true;
    }

    
        

    // Variables declaration - do not modify                     
    private javax.swing.JLabel CPF;
    private javax.swing.JFormattedTextField CPFField;
    private javax.swing.JButton CancelarB;
    private javax.swing.JButton DeletarB;
    private javax.swing.JButton EditarB;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel Endereco;
    private javax.swing.JTextField EnderecoField;
    private javax.swing.JLabel ID;
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel Nome;
    private javax.swing.JTextField NomeField;
    private javax.swing.JButton NovoB;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton PesquisarB;
    private javax.swing.JButton SalvarB;
    private javax.swing.JLabel Telefone;
    private javax.swing.JFormattedTextField TelefoneField;
    private javax.swing.JButton bTabela;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}